### ISSUE TITLE
Suggestion that we build another github

### ISSUE THREAD

**Issue by greatbody** [1995parham/github-do-not-ban-us#1033]
Programmers may build an independent GitHub in Switzerland, which is a permanent neutral country.

It is safer, and we can all donate a little for that.

We may no longer have GitHub pages, and many other features, but that's an warning to GitHub.

**Comment by PeaceBomber** [comment]
We need an open source Github. 
Support from China.

**Comment by mmahmoudian** [comment]
@greatbody I'm not a legal expert, but I think some international law experts should check if the assumption you have about "permanent neutrality" can hold for such cases.

Regardless, i think it must be a non-profit organization to avoid any trade laws. Something like Redcross or UNICEF that accepts donation and can provide humanitarian services (opensource is a humanitarian aspect of digital life), but can avoid any political non-sense.

----------

@PeaceBomber: it exists. one of the best examples is [Gitlab](https://gitlab.com/gitlab-org/gitlab-ce/)

**Comment by PeaceBomber** [comment]
> @greatbody I'm not a legal expert, but I think some international law experts should check if the assumption you have about "permanent neutrality" can hold for such cases.
> 
> Regardless, i think it must be a non-profit organization to avoid any trade laws. Something like Redcross or UNICEF that accepts donation and can provide humanitarian services (opensource is a humanitarian aspect of digital life), but can avoid any political non-sense.
> 
> @PeaceBomber: it exists. e.g [Gitlab](https://gitlab.com/gitlab-org/gitlab-ce/)

Is it a unlimit site for git without any political  non-sense?

**Comment by BelegCuthalion** [comment]
@PeaceBomber Hadn't GitLab migrated to Google Cloud, I would never return to GitHub. Google Cloud blocks Iranian IP ranges.

**Comment by PeaceBomber** [comment]
> @PeaceBomber Hadn't GitLab migrated to Google Cloud, I would never return to GitHub. Google Cloud blocks Iranian IP ranges.

Well, sounds bad for me. Google is a non-existent website in China. Maybe the best way to comunicate between developers is email. Lol.

**Comment by mmahmoudian** [comment]
@PeaceBomber Gitlab Community Edition is a software. you can download it from the link i gave you, install it on your server and host gitlab. So to be brief, Gitlab can be as unlimited and unpolitical as you are when you install it on your server

---------

@BelegCuthalion It is a shame that all major cloud providers are US-based companies (Amazon, Google, Digital Ocean, etc.) and other countries has to put up with the crap that US politics make. This Directly affects all other countries. i wonder why EU is not having a plan B to have infrastructure that they can rely on. So if someone put it on a server in a politically neutral country and does not use cloud services, then life gets better.

**Comment by khaninejad** [comment]
I am not expert here but blockchain and a decentralized solution would be the best like bitcoin!

**Comment by PeaceBomber** [comment]
@mmahmoudian I get it. However, it is the same for me to back my repos up in external disks. 

By the way, the saddest thing in this case, is that **we do not trust each other any more**. These politicians refuses to think and  learn anything they donot know.

**Comment by PeaceBomber** [comment]
> I am not expert here but blockchain and a decentralized solution would be the best like bitcoin!

@khaninejad **Banned by GitHub for being Iranian. What a Ridiculous Sentence. It reminds me that these Jewish were BANNED by NAZI for being Jewish. ** 

It is really the Historical retrogression and reenactment.

**Comment by a764934018** [comment]
Or you can use another platform which isn't from USA. Such as gitee.com. It's from China.

**Comment by mmahmoudian** [comment]
@a764934018 that is not the point here. China is yet another government with its own political situation. The idea is to have a git platform away from all possible political agendas, hence the suggestion of "Switzerland, which is a permanent neutral country." by @greatbody

**Comment by a764934018** [comment]
You are right. But there is no off-the-shelf solutions now. I just want to give a temporary solution for our friends of Iran.

**Comment by Alir3z4** [comment]
You don't need to build another Github from scratch and no, Gitlab is partially open source (_Gitlab is mostly useful to run for personal/group/organization usage and it's partially open source as well._).

You need a place to collaborate, otherwise why bother with gitlab/github/bitbucker/etc ? just keep them on your local machine and live a happy life.

Have a look at [Maybe an alternative like gitfoo.com ?](https://github.com/1995parham/github-do-not-ban-us/issues/913) where I proposed [GitFoo.com](https://gitfoo.com) to be an alternative.

It's completely open source and based on [gitea](https://github.com/go-gitea/gitea), I have enough resources to run and maintain it, it has enough feature and flexibility that will not make you miss GitHub.

**Comment by mmahmoudian** [comment]
For those who are wondering what @Alir3z4 is[ talking about](https://github.com/1995parham/github-do-not-ban-us/issues/1033#issuecomment-515931091), when stating:

> Gitlab is partially open source

As [Gitlab CEO stated](https://about.gitlab.com/2016/07/20/gitlab-is-open-core-github-is-closed-source/):

> paxcoder on Hacker News rightly remarked that calling it an open core company is more accurate. We ship **GitLab CE which is open source** and **GitLab EE that is closed source**. We try to be a good steward of the open source project. GitLab EE is proprietary, closed source code but we try to work in a way similar to GitLab CE: the issue tracker is publicly viewable and the EE license allows modifications.

The CE stands for Community Edition and the EE is the Enterprise Edition.

Therefore, at least according to [the text](https://about.gitlab.com/2016/07/20/gitlab-is-open-core-github-is-closed-source/) above, GitLab Community Edition is OpenSource and you can use it [as I mentioned](https://github.com/1995parham/github-do-not-ban-us/issues/1033#issuecomment-515883319).

**Comment by Alir3z4** [comment]
@mmahmoudian the statement of their CEO doesn't cover the situation correctly, you can check out https://about.gitlab.com/pricing/self-managed/feature-comparison/ and see the differences with the self-hosted "Core" and the rest.

Basically everything that makes GitLab a better place than Github requires a license and you cannot even obtain a license due to current sanctions.

**Comment by mmahmoudian** [comment]
I'd say [GitLab CE](https://about.gitlab.com/pricing/gitlab-com/feature-comparison/) has way more things to offer compared to Gitea, but I also confess that I personally admire the GUI of Gitea compared to GitLab.

Personally for me the "Built-in CI/CD" is very important and that is where Gitea fall behind:
https://docs.gitea.io/en-us/comparison/

Regardless, I bet having something is better than nothing, so if you have a server up and running and there are Devs who are willing to rebase to [GitFoo](https://gitfoo.com/) (pun intended), then problem is solved. I personally will wait, due to the reasons I mentioned [here](https://github.com/1995parham/github-do-not-ban-us/issues/913#issuecomment-515954244), and keep insisting on having GitFoo-likes in a land that somehow insures its stability.

**Comment by Alir3z4** [comment]
I agree with you, I've been using Gitlab for some years now and the UI is still not something that I can be comfortable with, the CI/CD feature is lovely especially when considering who flexible it can get with the container registery for docker flow (_mix with k8, it's a like love love love_).

However, even for CI/CD you have to setup CI runners if you wanna keep pushing, otherwise their shared service will be hammered you're out of free minutes.

Surely, I've moved most of my open source stuff to [GitFoo](https://gitfoo.com/) and already using private repos as well.

I'm surprised how light and easy is on the server resources (_considering golang_).

**Comment by a764934018** [comment]
@WaylanPunch gitee.com have english version, dude.

**Comment by xtlsoft** [comment]
And one more thing, a Chinese developer "无闻" built gogs: https://gogs.io
It is a self-hosted git server but it's liter.
And gitea.io, is a fork of Gogs and has a public demo.

**Comment by xtlsoft** [comment]
And the GitFoo guy is using Gitea.

**Comment by fakefred** [comment]
> It is a self-hosted git server but it's liter.

@xtlsoft What's "liter"?

**Comment by mmahmoudian** [comment]
> @xtlsoft What's "liter"?

I think @xtlsoft meant to say "lighter":
https://www.grammarly.com/blog/light-lite/

**Comment by fakefred** [comment]
@mmahmoudian Oh, thanks :) There's definitely too much physics thing going on in my mind

Country | US | UK | Russia | India
---|---|---|---|---
Bothers the FOSS community a lot | Yes | No | No | No
Usually uses imperial units | Yes | No | No | No

> COINCIDENCE?

**Comment by sullyfischer** [comment]
#1375

**Comment by scvoet** [comment]
Do you seem to be trying to re-establish a free platform using open source projects like GitLab and Gogs? This is really too bad. I think if you don't get a consensus, but you build a new platform. Not only does this not save the open source world, it also makes the situation even worse. Because each platform will be independent, developers will be diverted to various platforms. Developer contact will no longer be tight and will increase the difficulty of contributing code. Is this still the open source world we are familiar with?
I think the open source world should embrace distributed networks so that open source belongs to the world.✨
----------
你们似乎想使用GitLab、Gogs等开源项目重新建立一个自由的平台？这简直是恶梦。我认为如果没有获得共识，但却自行建立了一个新的平台。这不仅不能拯救开源世界，还会使得情况更加糟糕。因为每个平台都各自为政，开发者将会被分流到各个平台。开源项目之间的联系也会减少，同时增加我们贡献代码的难度。这还是我们所熟悉的开源世界吗？
我认为开源世界应该要拥抱分布式网络，这样开源才会属于全世界。✨

**Comment by DivySrivastava** [comment]
I suggest building another github.
We should start work on that.
Reply if anyone interested to join

**Comment by scvoet** [comment]
> I suggest building another github.
> We should start work on that.
> Reply if anyone interested to join

@DivySrivastava I think you better talk about what you plan to do first.
------------
我认为您最好先谈谈您打算怎么做。

**Comment by sullyfischer** [comment]
@scvoet I like the idea of decentralization, but _if_ we're going to start a new platform, it has to be up ASAP, and the only way to do so is by using an already established and tested source code such as https://github.com/gitlabhq/gitlabhq. Forking it tho, allows us to easily implement our own modifications. 

All the ideas such as decentralization can later be done as updates, forks, etc.

**Comment by Jshf** [comment]
> @scvoet I like the idea of decentralization, but _if_ we're going to start a new platform, it has to be up ASAP, and the only way to do so is by using an already established and tested source code such as https://github.com/gitlabhq/gitlabhq. Forking it tho, allows us to easily implement our own modifications.
> 
> All the ideas such as decentralization can later be done as updates, forks, etc.

This will require a lot of storage devices and enough network bandwidth, and you're sure you can afford it.

**Comment by FIREFOXCYBER** [comment]
We would need sometype of sponsorship for that.

**Comment by DivySrivastava** [comment]
> > @scvoet I like the idea of decentralization, but _if_ we're going to start a new platform, it has to be up ASAP, and the only way to do so is by using an already established and tested source code such as https://github.com/gitlabhq/gitlabhq. Forking it tho, allows us to easily implement our own modifications.
> > All the ideas such as decentralization can later be done as updates, forks, etc.
> 
> This will require a lot of storage devices and enough network bandwidth, and you're sure you can afford it.

True

**Comment by DivySrivastava** [comment]
> > I suggest building another GitHub.
> > We should start work on that.
> > Reply if anyone interested to join
> 
> ## @DivySrivastava I think you better talk about what you plan to do first.
> 我认为您最好先谈谈您打算怎么做。

Maybe we can create a basic git-hosting platform.
I and @dan-online are working on [GitChat](https://github.com/dan-divy/git-chat), a communication system for repos on Github. Maybe we can extend the project to a complete git-platform.
We can have basic repo creation, issue, etc features in that.
What do you think?

**Comment by scvoet** [comment]
> > > I suggest building another GitHub.
> > > We should start work on that.
> > > Reply if anyone interested to join
> > 
> > 
> > ## @DivySrivastava I think you better talk about what you plan to do first.
> > 我认为您最好先谈谈您打算怎么做。
> 
> Maybe we can create a basic git-hosting platform.
> I and @dan-online are working on [GitChat](https://github.com/dan-divy/git-chat), a communication system for repos on Github. Maybe we can extend the project to a complete git-platform.
> We can have basic repo creation, issue, etc features in that.
> What do you think?

It's good to use a ready-made program to build a new platform. But I think what we need most now is a leader to lead us to build a new platform. In addition, building a new platform requires financial and human support, and everything is not available. Our situation is very difficult now.
------------
暂时使用一个现成的程序搭建新平台这一 点很不错。但我想我们现在最需要的是一个领导者来带领我们完成搭建新平台。另外搭建新平台还需要资金和人力支持，一切都是没有的。我们现在的处境十分艰难。

**Comment by sullyfischer** [comment]
> > @scvoet I like the idea of decentralization, but _if_ we're going to start a new platform, it has to be up ASAP, and the only way to do so is by using an already established and tested source code such as https://github.com/gitlabhq/gitlabhq. Forking it tho, allows us to easily implement our own modifications.
> > All the ideas such as decentralization can later be done as updates, forks, etc.
> 
> This will require a lot of storage devices and enough network bandwidth, and you're sure you can afford it.

I started my previous project as a Reddit alternative. I was prepared for THAT amount of traffic! This requires the same, if not less.

For the future of it tho, yes we'll need some sorta sponsorship, donation, etc to survive.

**Comment by Alir3z4** [comment]
Building another github or running a similar website like github or gathering other dev to build similar thing is not the thing, 1 person can build a good functional system that "just works!"

You need hardware, network, funding, devOps, backup solutions, disaster recovery, scaling, innovate solutions, security, a GOOD AMOUNT OF SECURITY, expensive stuff and of course being on alert 24/7 everytime something is happening.

Other's infrastructure, software, packages, build systems and CIs will depend on you, they can't wait until you fix your website.

And a big bombastic, NO, you cannot survive with donation. It requires a lot of funding. Github is not even profitable, gitlab is not profitable, they're simply burning through cash until another company buys them out (_MS bought GH, so they survived I think_).

You can for sure get funding, get more devs working it, do marketing, people will eventually migrate to your new shiny git-hosting service, you'll success if you're doing good, now you need an exit, because well, you got funding from other companies and people, they expect a payback on their investment, someone buys you out, you'll hand it out to another company and that company will be subject to another set of sanctions or laws that will eventually restrict any other nation based on the local gov of that company.

The above is if you're damn great, I mean exceptionally good in what you do and you can exit.

Well, congrats you just repeated what GitHub did, now back to square one.

**Comment by scvoet** [comment]
> Building another github or running a similar website like github or gathering other dev to build similar thing is not the thing, 1 person can build a good functional system that "just works!"
> 
> You need hardware, network, funding, devOps, backup solutions, disaster recovery, scaling, innovate solutions, security, a GOOD AMOUNT OF SECURITY, expensive stuff and of course being on alert 24/7 everytime something is happening.
> 
> Other's infrastructure, software, packages, build systems and CIs will depend on you, they can't wait until you fix your website.
> 
> And a big bombastic, NO, you cannot survive with donation. It requires a lot of funding. Github is not even profitable, gitlab is not profitable, they're simply burning through cash until another company buys them out (_MS bought GH, so they survived I think_).
> 
> You can for sure get funding, get more devs working it, do marketing, people will eventually migrate to your new shiny git-hosting service, you'll success if you're doing good, now you need an exit, because well, you got funding from other companies and people, they expect a payback on their investment, someone buys you out, you'll hand it out to another company and that company will be subject to another set of sanctions or laws that will eventually restrict any other nation based on the local gov of that company.
> 
> The above is if you're damn great, I mean exceptionally good in what you do and you can exit.
> 
> Well, congrats you just repeated what GitHub did, now back to square one.

You are doing a good job. We conceived very well, but the reality is not as developed as we imagined. A completely neutral platform is now a utopian fantasy.
------------
您说的对。我们构想的很美好，但现实却不会像我们想象的所发展。完全中立的平台在现在就是一个乌托邦式的幻想。

**Comment by DivySrivastava** [comment]
I am on creating a git-platform using Node.js.
I think we should atleast try to run our GitHub and we'll see what happens. Will give updates on the project.

**Comment by our1314** [comment]
We need an real open source Github.

**Comment by mmahmoudian** [comment]
I agree with @Alir3z4 ([this post)](https://github.com/1995parham/github-do-not-ban-us/issues/1033#issuecomment-516901297) that making yet another git platform with conventional structure is a pointless act.

We, as Opensource community, already have [GitLab CE](https://gitlab.com/gitlab-org/gitlab-ce/), [gogs](https://gogs.io/) and [Gitea](https://gitea.io) and they all try to fill the same gap and they do it so damn good. What we really lack at this point of time is a distributed git platform (similar to what Mastodon and Disapora* do in the social network world).

@1995parham I suggest that this post is pointless and we should close this issue and all brainstorm/collaborate on [We have to federate git hosting services, asap](https://github.com/1995parham/github-do-not-ban-us/issues/629) where there are so many viable ideas.

**Comment by fakefred** [comment]
**Political problems need technological solutions.**

@1995parham This issue should be closed. Hooray for decentralization!

**Comment by 1995parham** [comment]
I will close this issue and everyone can have their ideas on #629
